In [1]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [3]:
#in 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
    

[1 2 3]
[4 5 6]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [15]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array([2,4,6,8,10,12,14])
c=a*b
print(c)


[ 2  8 18 32 50 72 98]


In [46]:
# import numpy as np

# a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [10, 20, 30, 40]])
# b = np.array([2, 4, 6, 8])  # Adjusted shape

# print("\nPrinting array a:")
# print(a)
# print("\nPrinting array b:")
# print(b)

# print("\nAdding array a and b:")
# c = a + b
# print("Array c:", c)



In [50]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[10,20,30,40]])
b=np.array([2,4,6,8])
print ("\n printing array a.")
print(a)
print ("\n printing array b.")
print(b)
print("\nAdding array a and b:")
c = a + b
print("Array c:", c)


 printing array a.
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]]

 printing array b.
[2 4 6 8]

Adding array a and b:
Array c: [[ 3  6  9 12]
 [ 7 10 13 16]
 [12 24 36 48]]
