In [3]:

import numpy as np
array1 =np.array([1,3,5])
array2 =np.array([2,4,6])

result = np.dot(array1,array2)
print(result)

44


In [5]:
import numpy as np
array1 =np.array([[1,3],
                  [5,7]])
array2 =np.array([[2,4],
                  [6,8]])
result=np.inner(array1,array2)
print (result)

[[14 30]
 [38 86]]


In [7]:
#outer()
array1 =np.array([1,3,5])
array2 =np.array([2,4,6]) 
result = np.outer(array1,array2)
print(result)

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [9]:
#det()
array1 =np.array([[1,3],
                  [5,7]])
result= np.linalg.det(array1)
print(result)

-7.999999999999998


In [11]:
#solve()
A=np.array([[2,4],
            [6,8]])
B=np.array([5,6])
x=np.linalg.solve(A,B)
print(x)

[-2.    2.25]


In [13]:
#inv function
array1 =np.array([[2,4],
                  [6,8]])
result=np.linalg.inv(array1)
print(result)

[[-1.    0.5 ]
 [ 0.75 -0.25]]


In [15]:
#trace() function
import numpy as np
array1 =np.array([[6,3,5],
                   [9,2,1],
                   [7,8,4]])
result =np.trace(array1)
print(result)

12


In [17]:
#Minima
from scipy.optimize import minimize

def eqn(x):
    return x**2+x+2
mymin = minimize(eqn,0,method='BFGS')
print(mymin)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.75
        x: [-5.000e-01]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.000e-01]]
     nfev: 8
     njev: 4
