In [1]:
#import numpy as np
#print(np.__version__)

1.26.4


In [9]:
#3D
#arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
#print(arr)


In [14]:
#0D
# import numpy as np
# arr=np.array(42)
# print(arr)

In [16]:
#1D
# import numpy as np
# arr=np.array([1,2,3])
# print(arr)

[1 2 3]


In [18]:
#2D
# import numpy as np
# arr=np.array([[1,2,3],[4,5,6]])
# print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
# To check the diamention
# import numpy as np
# a=np.array(42)
# b=np.array([1,2,3])
# c=np.array([[1,2,3],[4,5,6]])
# d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

# print(a.ndim)
# print(b.ndim)
# print(c.ndim)
# print(d.ndim)

0
1
2
3
