In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
import numpy as np
print(np.__version__)

1.26.4


In [11]:
#INDEXING
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [13]:
#3d INDEXING
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

[2 3 4 5]


In [23]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [25]:
#to check data type
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [31]:
#convert to string data type
import numpy as np
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1
